"""Reset generated vault artifacts and internal state."""

from __future__ import annotations

import shutil
from datetime import datetime, timezone
from pathlib import Path

from app.config import get_settings
from app.storage.sqlite import Database
from app.vault.paths import RESETTABLE_DIRS, ensure_vault_dirs


def reset_generated_state(*, archive_existing: bool = True) -> dict[str, str | list[str]]:
    """Clear generated vault content and generated SQLite/search state.

    Keeps the vault root, AGENTS.md, and user configuration intact.
    Optionally archives the previous generated artifacts under `.system/archives/`.
    """

    settings = get_settings()
    vault_path = Path(settings.vault_path)
    vault_path.mkdir(parents=True, exist_ok=True)
    ensure_vault_dirs(vault_path)

    archive_root = ""
    if archive_existing:
        archive_name = datetime.now(timezone.utc).strftime("generated-reset-%Y%m%d-%H%M%S")
        archive_root = str(vault_path / ".system" / "archives" / archive_name)

    cleared: list[str] = []
    for relative_dir in RESETTABLE_DIRS:
        target = vault_path / relative_dir
        if not target.exists():
            continue

        if archive_existing and _path_has_content(target):
            destination = Path(archive_root) / relative_dir
            destination.parent.mkdir(parents=True, exist_ok=True)
            shutil.copytree(target, destination, dirs_exist_ok=True)

        if target.is_dir():
            shutil.rmtree(target)
        else:
            target.unlink(missing_ok=True)
        cleared.append(relative_dir)

    ensure_vault_dirs(vault_path)
    _write_index_placeholders(vault_path)
    _write_log_placeholders(vault_path)
    _reset_database(settings.db_path)

    return {
        "vault_path": str(vault_path),
        "archive_path": archive_root,
        "cleared": cleared,
    }


def _path_has_content(path: Path) -> bool:
    if path.is_file():
        return path.stat().st_size > 0
    return any(path.iterdir())


def _write_index_placeholders(vault_path: Path) -> None:
    placeholders = {
        "INDEX.md": "# INDEX\n\n_Empty — will be populated after first ingest._\n",
        "TOPICS.md": "# TOPICS\n\n_Empty — will be populated after first ingest._\n",
        "ENTITIES.md": "# ENTITIES\n\n_Empty — will be populated after first ingest._\n",
        "CONCEPTS.md": "# CONCEPTS\n\n_Empty — will be populated after first ingest._\n",
    }
    for filename, content in placeholders.items():
        path = vault_path / "wiki" / "indexes" / filename
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")


def _write_log_placeholders(vault_path: Path) -> None:
    placeholders = {
        "ingest-log.md": "# Ingest Log\n\nAppend-only log.\n\n---\n\n",
        "lint-log.md": "# Lint Log\n\nGenerated by the lint workflow.\n\n---\n\n",
    }
    for filename, content in placeholders.items():
        path = vault_path / "wiki" / "logs" / filename
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")


def _reset_database(db_path: Path) -> None:
    db = Database(db_path)
    db.connect()
    try:
        db.conn.execute("DELETE FROM processed_sources")
        db.conn.execute("DELETE FROM vault_notes")
        db.conn.execute("DELETE FROM sync_cursors")
        db.conn.commit()
    finally:
        db.close()
